[workspace]
members = [
    "dir-structure",
    "dir-structure-macros",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2024"
homepage = "https://nrx.dnbln.dev/docs/dx/dir-structure/"
repository = "https://github.com/dnbln/dir-structure"
description = "Model directory structures as plain Rust structs."
keywords = ["file-system"]
license = "MIT OR Apache-2.0"


[workspace.dependencies]
assert_eq_macros = { version = "=0.2.0" }
assert_eq = { version = "0.2.0" }
dir-structure-macros = { path = "dir-structure-macros", version = "=0.2.0" }
dir-structure = { path = "dir-structure", version = "0.2.0" }

bumpalo = "3.6.0"
bytes = "1.4.0"
cargo_metadata = "0.19.1"
nextest-metadata = "0.12.1"
clap = { version = "4.5.48", features = ["derive"] }
clap_complete = "4.5.58"
clap_mangen = "0.2.26"
criterion = { version = "0.5", features = ["html_reports"] }
bitflags = "2"
dashmap = "6.1.0"
drop_bomb = "0.1.5"
human-panic = "2.0.0"
humantime = "2.3.0"
git2 = { version = "0.20", default-features = false }
libc = "0.2"
libtest-mimic = "0.8.1"
llvm-sys = { version = "211.0.0", default-features = false }
miette = { version = "7.2.0", features = ["fancy"] }
owo-colors = { version = "4.0.0", features = ["supports-colors"] }
path-absolutize = "3.1.1"
pin-project = { version = "1", default-features = false }
prodash = { version = "29.0.0", default-features = false, features = [
    "render-line",
    "render-line-crossterm",
    "render-line-autoconfigure",
    "progress-tree",
] }
reqwest = { version = "0.12.15", features = ["blocking"] }
rowan = "0.16.1"
salsa = { path = "src/compiler/narxia-salsa" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
similar = "2.7"
smallvec = "1.10.0"
tar = "0.4"
thiserror = "2.0.12"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tokio = { version = "1", features = ["full"] }
liblzma = "0.4.0"
zip = "4"
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[workspace.lints.rust]
unsafe_code = "deny"
unused_imports = "deny"
unused_unsafe = "deny"
mismatched_lifetime_syntaxes = "deny"
stable_features = "deny"


[workspace.lints.clippy]
absolute_paths = "deny"
alloc_instead_of_core = "deny"
allow_attributes = "deny"
suspicious = { level = "deny", priority = -1 }
style = "deny"
useless_format = "deny"
