[workspace]
members = ["src/compiler/*", "src/dev/*"]
default-members = ["src/dev/cargo-guard"]
resolver = "2"

[workspace.package]
version = "0.0.0"
publish = false
edition = "2024"
homepage = "https://nrx.dnbln.dev/"
repository = "https://github.com/dnbln/narxia"
description = "A programming language for distributed systems."
keywords = ["narxia", "programming-language"]
license = "MIT OR Apache-2.0"

[profile.release]
debug = true

[profile.dev.package."rowan"]
opt-level = 3

[profile.dev.package."libtest-mimic"]
opt-level = 3

[profile.dev.package."narxia-syn"]
opt-level = 3

[workspace.dependencies]
narxia-codegen = { path = "src/compiler/narxia-codegen" }
narxia-codegen-llvm = { path = "src/compiler/narxia-codegen-llvm" }
narxia-data-structures = { path = "src/compiler/narxia-data-structures" }
narxia-workspace = { path = "src/dev/narxia-workspace" }
narxia-driver = { path = "src/compiler/narxia-driver" }
narxia-hir = { path = "src/compiler/narxia-hir" }
narxia-hir-lower = { path = "src/compiler/narxia-hir-lower" }
narxia-hir-db = { path = "src/compiler/narxia-hir-db" }
narxia-hir-typechk = { path = "src/compiler/narxia-hir-typechk" }
narxia-hiri = { path = "src/compiler/narxia-hiri" }
narxia-log = { path = "src/compiler/narxia-log" }
narxia-log-impl = { path = "src/compiler/narxia-log-impl" }
narxia-proc = { path = "src/compiler/narxia-proc" }
narxia-src-db = { path = "src/compiler/narxia-src-db" }
narxia-ssa = { path = "src/compiler/narxia-ssa" }
narxia-ssa-lower = { path = "src/compiler/narxia-ssa-lower" }
narxia-ssa-validator = { path = "src/compiler/narxia-ssa-validator" }
narxia-syn = { path = "src/compiler/narxia-syn" }
narxia-syn-db = { path = "src/compiler/narxia-syn-db" }

assert_eq_macros = { path = "src/dev/assert_eq_macros", version = "=0.1.0" }
assert_eq = { path = "src/dev/assert_eq", version = "0.1.0" }
doc-extract = { path = "src/dev/doc-extract" }
dir-structure-macros = { path = "src/dev/dir-structure-macros", version = "=0.2.0-rc.2" }
dir-structure = { path = "src/dev/dir-structure", version = "0.2.0-rc.2" }
git-journey = { path = "src/dev/git-journey", version = "0.1.0" }
git-voyage = { path = "src/dev/git-voyage", version = "0.1.0" }

bumpalo = "3.6.0"
cargo_metadata = "0.19.1"
nextest-metadata = "0.12.1"
clap = { version = "4.4.3", features = ["derive"] }
clap_complete = "4.5.50"
clap_mangen = "0.2.26"
criterion = { version = "0.5", features = ["html_reports"] }
bitflags = "2"
dashmap = "6.1.0"
drop_bomb = "0.1.5"
human-panic = "2.0.0"
humantime = "2.1.0"
git2 = { version = "0.20", default-features = false }
libc = "0.2"
libtest-mimic = "0.8.1"
llvm-sys = { version = "201.0.0", default-features = false }
miette = { version = "7.2.0", features = ["fancy"] }
owo-colors = { version = "4.0.0", features = ["supports-colors"] }
path-absolutize = "3.1.1"
pin-project = { version = "1", default-features = false }
prodash = { version = "29.0.0", default-features = false, features = [
    "render-line",
    "render-line-crossterm",
    "render-line-autoconfigure",
    "progress-tree",
] }
reqwest = { version = "0.12.15", features = ["blocking"] }
rowan = "0.16.1"
salsa = { path = "src/compiler/narxia-salsa" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
similar = "2.7"
smallvec = "1.10.0"
tar = "0.4"
thiserror = "2.0.12"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tokio = { version = "1", features = ["full"] }
liblzma = "0.4.0"
zip = "4"
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[workspace.lints.rust]
unsafe_code = "deny"
unused_imports = "deny"
unused_unsafe = "deny"
mismatched_lifetime_syntaxes = "deny"
stable_features = "deny"


[workspace.lints.clippy]
absolute_paths = "deny"
alloc_instead_of_core = "deny"
allow_attributes = "deny"
suspicious = { level = "deny", priority = -1 }
style = "deny"
useless_format = "deny"
