[package]
name = "assert_eq"
version = "0.1.0"
publish = true
edition.workspace = true
homepage.workspace = true
repository = "https://github.com/dnbln/narxia/tree/trunk/src/dev/assert_eq"
description = "assert_eq: location-aware equality assertions"
keywords = ["assert_eq", "testing", "debugging"]
license.workspace = true

[features]
default = ["std"]
nightly = []
std = []

[dependencies]
assert_eq_macros.workspace = true

[lints]
workspace = true
