[package]
name = "narxia-codegen-llvm"
version.workspace = true
publish.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true
license.workspace = true

[lints]
workspace = true

[features]
default = []
llvm-force-static = ["llvm-sys/force-static"]
llvm-prefer-dynamic = ["llvm-sys/prefer-dynamic"]
llvm-force-dynamic = ["llvm-sys/force-dynamic"]

[dependencies]
narxia-codegen.workspace = true
narxia-log.workspace = true

libc.workspace = true
llvm-sys.workspace = true
