[package]
name = "dir-structure-macros"
version = "0.3.0"
edition = "2024"
homepage = "https://nrx.dnbln.dev/docs/dx/dir-structure/"
repository = "https://github.com/dnbln/dir-structure"
description = "dir-structure: proc-macros"
keywords = ["file-system"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[features]
async = []
resolve-path = ["dep:dir-structure-resolve-core"]
include_dir_vfs = []

[dependencies]
quote.workspace = true
syn.workspace = true
proc-macro2.workspace = true
dir-structure-resolve-core = { workspace = true, optional = true }

[lints]
workspace = true
