[package]
name = "narxia-syn-db"
version.workspace = true
publish.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
salsa.workspace = true

narxia-log.workspace = true
narxia-src-db.workspace = true
narxia-syn.workspace = true
