[package]
name = "dir-structure-include-dir-vfs"
version = "0.3.0"
edition = "2024"
homepage = "https://nrx.dnbln.dev/docs/dx/dir-structure/"
repository = "https://github.com/dnbln/dir-structure"
description = "Model directory structures as plain Rust structs."
keywords = ["file-system"]
license = "MIT OR Apache-2.0"

[dependencies]
dir-structure.workspace = true
include_dir = { version = "0.7", default-features = false }

[dev-dependencies]
dir-structure = { workspace = true, features = ["derive"] }

[lints]
workspace = true
