[package]
name = "dir-structure-macros"
version = "0.2.0-rc.1"
edition.workspace = true
license = "MIT OR Apache-2.0"
description = "dir-structure: proc-macros"
repository = "https://github.com/dnbln/narxia/tree/trunk/src/dev/dir-structure-macros"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[features]
async = []
resolve-path = []

[dependencies]
syn = { version = "2", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[lints]
workspace = true
