[package]
name = "doc-patchup"
version.workspace = true
publish = false
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true
license.workspace = true

[dependencies]
doc-extract.workspace = true
tokio.workspace = true
glob.workspace = true
thiserror.workspace = true

[lints]
workspace = true
