[package]
name = "git-voyage"
version = "0.1.0"
publish = true
edition.workspace = true
homepage = "https://nrx.dnbln.dev/docs/dx/git-voyage"
repository = "https://github.com/dnbln/narxia/tree/trunk/dev/git-voyage"
description = "Programming guide patching tool"
keywords = ["git"]
license.workspace = true

[dependencies]
git2 = { version = "0.20" }
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
dir-structure.workspace = true
thiserror.workspace = true

[lints]
workspace = true
