[package]
name = "dir-structure-resolve-core"
version = "0.3.0"
edition = "2024"
homepage = "https://nrx.dnbln.dev/docs/dx/dir-structure/"
repository = "https://github.com/dnbln/dir-structure"
description = "Model directory structures as plain Rust structs."
keywords = ["file-system"]
license = "MIT OR Apache-2.0"

[dependencies]

[lints]
workspace = true
