[alias]
nt = "nextest run"
nta = "nt --workspace"
nexus = "run -p nexus --"
nexusr = "run -p nexus --release --"

[unstable]
codegen-backend = true

# [profile.dev]
# codegen-backend = "cranelift"

[target.'cfg(debug_assertions)']
rustflags = [
    "--cfg", "hir_id_span",
    "--cfg", "hir_id_deeptree",
]

[target.'cfg(all())']
rustflags = [
    "-Zshare-generics=y",
    "-Zmacro-backtrace",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-Clink-arg=-fuse-ld=lld",
]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = [
	"-C", "link-arg=/STACK:16000000"
]

[target.x86_64-apple-darwin]
rustflags = [
    "-Csplit-debuginfo=unpacked",
]
