[target.'cfg(all())']
rustflags = [
    "-Zshare-generics=y",
    "-Zmacro-backtrace",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-Clink-arg=-fuse-ld=lld",
]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[target.x86_64-apple-darwin]
rustflags = [
    "-Csplit-debuginfo=unpacked",
]