[package]
name = "narxia-hir-typechk"
version.workspace = true
publish.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
narxia-hir.workspace = true
narxia-log.workspace = true
narxia-data-structures.workspace = true
narxia-src-db.workspace = true
narxia-src-db-impl.workspace = true

annotate-snippets.workspace = true
anstream = "0.6.21"
