[package]
name = "narxia-src-db-impl"
version.workspace = true
publish.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true
license.workspace = true

[dependencies]
path-absolutize.workspace = true

[lints]
workspace = true
