[package]
name = "dir-structure"
version = "0.2.0-rc.2"
edition.workspace = true
license = "MIT OR Apache-2.0"
description = "Simple crate to create and model directory structures."
repository = "https://github.com/dnbln/narxia/tree/trunk/src/dev/dir-structure"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
json = ["dep:serde", "dep:serde_json"]
toml = ["dep:serde", "dep:toml"]
yaml = ["dep:serde", "dep:serde_yaml"]
ron = ["dep:serde", "dep:ron"]
async = ["dep:pin-project", "dep:futures", "dir-structure-macros/async"]
tokio = ["dep:tokio", "async"]
include_dir = ["dep:include_dir"]
git = ["dep:git2"]
resolve-path = ["dir-structure-macros/resolve-path"]
image = ["dep:image", "tokio/rt"]
image-format-png = ["image", "image/png"]
image-format-gif = ["image", "image/gif"]
image-format-jpeg = ["image", "image/jpeg"]
image-format-webp = ["image", "image/webp"]
image-format-tiff = ["image", "image/tiff"]
image-format-tga = ["image", "image/tga"]
image-format-bmp = ["image", "image/bmp"]
image-format-ico = ["image", "image/ico"]
image-format-hdr = ["image", "image/hdr"]
image-format-exr = ["image", "image/exr"]
image-format-pnm = ["image", "image/pnm"]
image-format-ff = ["image", "image/ff"]
image-format-avif = ["image", "image/avif"]
image-format-qoi = ["image", "image/qoi"]
assert_eq = ["dep:assert_eq"]
_all = [
    "json",
    "toml",
    "yaml",
    "ron",
    "async",
    "tokio",
    "include_dir",
    "git",
    "resolve-path",
    "image",
    "image-format-png",
    "image-format-gif",
    "image-format-jpeg",
    "image-format-webp",
    "image-format-tiff",
    "image-format-tga",
    "image-format-bmp",
    "image-format-ico",
    "image-format-hdr",
    "image-format-exr",
    "image-format-pnm",
    "image-format-ff",
    "image-format-avif",
    "image-format-qoi",
    "assert_eq",
]

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[dependencies]
dir-structure-macros.workspace = true
futures = { version = "0.3", optional = true, default-features = false, features = [
    "io-compat",
] }
thiserror.workspace = true
pin-project = { workspace = true, optional = true }
ron = { version = "0.8", optional = true, default-features = false }
serde = { version = "1.0", optional = true, default-features = false, features = [
    "derive",
    "std",
] }
serde_json = { version = "1.0", optional = true, default-features = false, features = [
    "std",
] }
serde_yaml = { version = "0.9", optional = true, default-features = false }
toml = { version = "0.8", optional = true, default-features = false, features = [
    "display",
    "parse",
] }
tokio = { version = "1", optional = true, default-features = false, features = [
    "fs",
    "io-util",
] }
include_dir = { version = "0.6", optional = true, default-features = false }
image = { version = "0.25", optional = true, default-features = false }
assert_eq = { workspace = true, optional = true }
git2 = { workspace = true, optional = true }

[[test]]
name = "async_tests"
path = "tests/async_tests.rs"
required-features = ["async", "tokio", "assert_eq"]

[[test]]
name = "tests"
path = "tests/tests.rs"
required-features = ["assert_eq"]

[[example]]
name = "reading_from_include_dir_vfs"
path = "examples/reading_from_include_dir_vfs.rs"
required-features = ["include_dir"]

[[example]]
name = "reading_dir_children_from_include_dir_vfs"
path = "examples/reading_dir_children_from_include_dir_vfs.rs"
required-features = ["include_dir"]

[[example]]
name = "reading_from_git_vfs"
path = "examples/reading_from_git_vfs.rs"
required-features = ["git"]

[[example]]
name = "reading_from_tokio_fs_vfs"
path = "examples/reading_from_tokio_fs_vfs.rs"
required-features = ["tokio", "async"]

[[example]]
name = "writing_to_tokio_fs_vfs"
path = "examples/writing_to_tokio_fs_vfs.rs"
required-features = ["tokio", "async"]

[lints]
workspace = true
