[package]
name = "dir-structure-git-vfs"
version.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true
license.workspace = true

[dependencies]
dir-structure.workspace = true
git2.workspace = true

[lints]
workspace = true
