[package]
name = "narxia-hir-db"
version.workspace = true
publish.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lints]
workspace = true

[dependencies]
salsa.workspace = true
narxia-syn-db.workspace = true
narxia-hir.workspace = true
narxia-hir-lower.workspace = true
