.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH nrx-comp 1  "comp " 
.SH NAME
nrx\-comp
.SH SYNOPSIS
\fBnrx comp\fR [\fB\-h\fR|\fB\-\-help\fR] <\fISHELL\fR> 
.SH DESCRIPTION
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fISHELL\fR>

.br
[\fIpossible values: \fRbash, elvish, fish, powershell, zsh]
