.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH nrx-parse 1  "parse " 
.SH NAME
nrx\-parse \- Parse the given file
.SH SYNOPSIS
\fBnrx parse\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Parse the given file.
.PP
This command will parse the given file and print the resulting syntax tree.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fIFILE\fR>

