.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH nrx 1  "nrx 0.0.0" 
.SH NAME
nrx \- Compiler for narxia
.SH SYNOPSIS
\fBnrx\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Compiler for narxia
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
nrx\-parse(1)
Parse the given file
.TP
nrx\-display\-hir(1)
.TP
nrx\-display\-hir\-debug(1)
.TP
nrx\-hiri(1)
.TP
nrx\-sema\-analysis(1)
.TP
nrx\-codegen(1)
.TP
nrx\-ssa(1)
.TP
nrx\-comp(1)
.TP
nrx\-man\-gen(1)
.SH VERSION
v0.0.0
