name: Test dir structure
description: Test the dir-structure crate with various feature combinations

inputs:
  feature-combos:
    description: Feature combinations to test
    required: true

runs:
  using: "composite"
  steps:
    - name: Run tests
      run: cargo test -p dir-structure -p dir-structure-macros -p dir-structure-tools -p dir-structure-include-dir-vfs -p dir-structure-git-vfs -p dir-structure-resolve-core ${{ inputs.feature-combos }} -- --test-threads=1
      shell: bash