[package]
name = "dir-structure"
version.workspace = true
edition.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["derive", "_all"]
async = ["dep:pin-project", "dep:futures", "dir-structure-macros?/async"]
tokio = ["dep:tokio", "async"]
include_dir = [
    "dep:include_dir",
    "dir-structure-macros/include_dir_vfs", # need workaround until https://github.com/Michael-F-Bryan/include_dir/pull/115 for the include_dir_vfs! macro
]
git = ["dep:git2"]
resolve-path = ["dir-structure-macros?/resolve-path", "dep:dir-structure-resolve-core"]
assert_eq = ["dep:assert_eq"]
derive = ["dep:dir-structure-macros"]

_all = [
    "async",
    "tokio",
    "include_dir",
    "git",
    "resolve-path",
    "assert_eq",
    "derive",
]

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[dependencies]
dir-structure-macros = { workspace = true, optional = true }
dir-structure-resolve-core = { workspace = true, optional = true }
futures = { version = "0.3", optional = true, default-features = false, features = [
    "io-compat",
] }
pin-project = { workspace = true, optional = true }
tokio = { version = "1", optional = true, default-features = false, features = [
    "fs",
    "io-util",
] }
include_dir = { version = "0.7", optional = true, default-features = false }
assert_eq = { workspace = true, optional = true }
git2 = { workspace = true, optional = true }

[lints]
workspace = true

[[example]]
name = "reading_from_tokio_fs_vfs"
path = "examples/reading_from_tokio_fs_vfs.rs"
required-features = ["tokio", "async", "derive"]

[[example]]
name = "writing_to_tokio_fs_vfs"
path = "examples/writing_to_tokio_fs_vfs.rs"
required-features = ["tokio", "async", "derive"]

[[example]]
name = "resolve_path"
path = "examples/resolve_path.rs"
required-features = ["resolve-path", "derive"]

[[example]]
name = "load_path"
path = "examples/load_path.rs"
required-features = ["resolve-path", "derive"]

[[example]]
name = "std_fs_vfs"
path = "examples/std_fs_vfs.rs"
required-features = ["derive"]

[[example]]
name = "reading_from_include_dir_vfs"
path = "examples/reading_from_include_dir_vfs.rs"
required-features = ["include_dir"]

[[example]]
name = "reading_from_git_vfs"
path = "examples/reading_from_git_vfs.rs"
required-features = ["git"]