[package]
name = "narxia-workspace"
version.workspace = true
publish.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true


[lints]
workspace = true

[dependencies]
dir-structure = { workspace = true, features = ["derive", "resolve-path", "tools"] }
