name: Push Nightly
on:
    schedule:
        - cron: '0 0 * * *'  # Every day at midnight UTC
    workflow_dispatch:  # Allow manual triggering of the workflow


jobs:
    push-nightly:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Push to nightly branch
              run: |
                git branch -D nightly || true
                git checkout -b nightly
                git push origin nightly