name: Test

on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install rust
        run: rustup install nightly && rustup default nightly
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
          args: --locked
      # - name: Rust cache
      #   uses: Swatinem/rust-cache@v2
      - name: Build nexus
        run: cargo build -p nexus
      # - name: Build
      #   run: cargo nexus build-sys build
      # - name: Test
      #   run: cargo nexus test --no-fail-fast
      - name: Build
        run: cargo build -p narxia-driver --bin narxia-driver
      - name: Test
        run: cargo nextest run --all
