name: Dir-Structure Tests

on:
  push:
    branches: ["trunk"]
    paths:
      - 'src/dev/dir-structure/src/**'
      - 'src/dev/dir-structure/Cargo.toml'
      - 'src/dev/dir-structure/README.md'
      - 'src/dev/dir-structure/tests/**'
      - 'src/dev/dir-structure/examples/**'
      - 'src/dev/dir-structure-macros/**'
      - 'doc/docs/content/docs/dev/dir-structure/*.doctests'
      - '.github/workflows/test-dir-structure.yml'
  pull_request:
    branches: ["trunk"]
    paths:
      - 'src/dev/dir-structure/src/**'
      - 'src/dev/dir-structure/Cargo.toml'
      - 'src/dev/dir-structure/README.md'
      - 'src/dev/dir-structure/tests/**'
      - 'src/dev/dir-structure/examples/**'
      - 'src/dev/dir-structure-macros/**'
      - 'doc/docs/content/docs/dev/dir-structure/*.doctests'
      - '.github/workflows/test-dir-structure.yml'

env:
  CARGO_TERM_COLOR: always
  COLOR: always
  NEXUS_GROUP_BEGIN: "::group::{group}"
  NEXUS_GROUP_END: "::endgroup::"
  CC: clang
  CXX: clang++

jobs:
  test:
    name: Test dir-structure
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature-combos: [
            "--no-default-features",
            "--no-default-features --features assert_eq",
            "--no-default-features --features git",
            "--no-default-features --features async",
            "--no-default-features --features tokio",
            "--no-default-features --features image",
            "--no-default-features --features image,image-format-png",
            "--no-default-features --features image,image-format-jpeg",
            "--no-default-features --features resolve-path",
            "--no-default-features --features json",
            "--no-default-features --features toml",
            "--no-default-features --features yaml",
            "--no-default-features --features ron",
            "--no-default-features --features include_dir",
            "--no-default-features --features derive",
            "--no-default-features --features tools",
            "--features assert_eq",
            "--features assert_eq,git",
            "--features assert_eq,async",
            "--features assert_eq,tokio",
            "--features assert_eq,image",
            "--features assert_eq,image,image-format-png",
            "--features assert_eq,async,image",
            "--features assert_eq,tokio,image",
            "--features assert_eq,tokio,image,image-format-png",
            "--features assert_eq,resolve-path",
            "--features assert_eq,tokio,resolve-path",
            "--features assert_eq,json,toml,yaml,ron",
            "--features assert_eq,async,json,toml,yaml,ron",
            "--features assert_eq,tokio,json,toml,yaml,ron",
            "--features assert_eq,include_dir",
            "--all-features",
        ]
        cmd: [ "build", "test" ]

    steps:
      - uses: actions/checkout@v4
    #   - name: Install dependencies
    #     run: sudo apt update && sudo apt install openssl libssl-dev
      - name: Install rust
        run: rustup install nightly && rustup default nightly
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ matrix.feature-combos == '--all-features' && matrix.cmd == 'test' }}
      - name: Build dir-structure
        run: cargo build -p dir-structure ${{ matrix.feature-combos }}
        if: matrix.cmd == 'build'

      - name: Run tests
        run: cargo test -p dir-structure ${{ matrix.feature-combos }} -- --test-threads=1
        if: matrix.cmd == 'test'
