name: Dir-Structure Tests

on:
  push:
    branches: ["trunk"]
    paths:
      - 'src/dev/dir-structure/**'
      - 'src/dev/dir-structure-macros/**'
      - 'doc/docs/content/docs/dev/dir-structure/*.doctests'
      - '.github/workflows/test-dir-structure.yml'
  pull_request:
    branches: ["trunk"]
    paths:
      - 'src/dev/dir-structure/**'
      - 'src/dev/dir-structure-macros/**'
      - 'doc/docs/content/docs/dev/dir-structure/*.doctests'
      - '.github/workflows/test-dir-structure.yml'

env:
  CARGO_TERM_COLOR: always
  COLOR: always
  NEXUS_GROUP_BEGIN: "::group::{group}"
  NEXUS_GROUP_END: "::endgroup::"
  CC: clang
  CXX: clang++

jobs:
  test:
    name: Test dir-structure
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature-combos: [
            "--features default",
            "--features assert_eq,default",
            "--features assert_eq,default,git",
            "--features assert_eq,async",
            "--features assert_eq,tokio",
            "--features assert_eq,image",
            "--features assert_eq,image,image-format-png",
            "--features assert_eq,image,image-format-jpeg",
            "--features assert_eq,async,image",
            "--features assert_eq,tokio,image",
            "--features assert_eq,tokio,image,image-format-png",
            "--features assert_eq,tokio,image,image-format-jpeg",
            "--features assert_eq,resolve-path",
            "--features assert_eq,async,resolve-path",
            "--features assert_eq,tokio,resolve-path",
            "--features assert_eq,async,tokio,resolve-path",
            "--features assert_eq,json",
            "--features assert_eq,async,json",
            "--features assert_eq,tokio,json",
            "--features assert_eq,toml",
            "--features assert_eq,async,toml",
            "--features assert_eq,tokio,toml",
            "--features assert_eq,yaml",
            "--features assert_eq,async,yaml",
            "--features assert_eq,tokio,yaml",
            "--features assert_eq,ron",
            "--features assert_eq,async,ron",
            "--features assert_eq,tokio,ron",
            "--features assert_eq,include_dir",
            "--features assert_eq,async,include_dir",
            "--all-features",
        ]
        cmd: [ "build", "test" ]

    steps:
      - uses: actions/checkout@v4
    #   - name: Install dependencies
    #     run: sudo apt update && sudo apt install openssl libssl-dev
      - name: Install rust
        run: rustup install nightly && rustup default nightly
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ matrix.feature-combos == '--all-features' && matrix.cmd == 'test' }}
      - name: Build dir-structure
        run: cargo build -p dir-structure --no-default-features ${{ matrix.feature-combos }}
        if: matrix.cmd == 'build'

      - name: Run tests
        run: cargo test -p dir-structure --no-default-features ${{ matrix.feature-combos }} -- --test-threads=1
        if: matrix.cmd == 'test'
