name: Test

on:
  push:
    branches: ["trunk"]
  pull_request:
    branches: ["trunk"]

env:
  CARGO_TERM_COLOR: always
  COLOR: always
  NEXUS_GROUP_BEGIN: "::group::{group}"
  NEXUS_GROUP_END: "::endgroup::"
  CC: clang
  CXX: clang++

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup debug environment variables
        if: ${{ runner.debug == '1' }}
        run: |
          echo "NEXUS_DEBUG_NEXTEST_OUTPUT=1" >> $GITHUB_ENV
      - name: Install dependencies
        run: sudo apt update && sudo apt install clang ninja-build openssl libssl-dev
      - name: Install rust
        run: rustup install nightly && rustup default nightly && rustup component add rustfmt clippy
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-nextest
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Build nexus
        run: cargo build -p nexus
      - uses: ./.github/actions/build-llvm
      - name: Build narxia
        run: cargo nexus build-sys build --targets compiler
      - name: Build tests
        run: cargo nexus build-sys build --targets tests
      - name: Test
        run: cargo nexus test --no-fail-fast
        timeout-minutes: 3
      - name: Test rustdoc
        run: cargo nexus doctest --no-fail-fast
      - name: Format check
        run: cargo nexus build-sys fmt --check
      - name: Lint
        run: cargo nexus build-sys lint
